"""Generate ``src/neurolayer/core/positions.py`` from MNE's colin27_1005 template.

Positions are unit vectors (head-centered, normalized) for every canonical channel name
in ``neurolayer.core.channels`` that the template defines. Source: MNE-Python
``make_standard_montage("colin27_1005")`` (BSD-3-Clause). Re-run only if the canonical
name list changes.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from neurolayer.core.channels import _STANDARD_NAMES

TARGET = Path(__file__).resolve().parents[1] / "src" / "neurolayer" / "core" / "positions.py"


def main() -> int:
    """Write the positions module."""
    import mne

    positions = mne.channels.make_standard_montage("colin27_1005").get_positions()["ch_pos"]
    lines = [
        '"""Unit-sphere electrode positions for canonical channel names (generated file).',
        "",
        "Generated by ``scripts/make_electrode_positions.py`` from MNE-Python's colin27_1005",
        "template (BSD-3-Clause). Do not edit by hand.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "POSITIONS: dict[str, tuple[float, float, float]] = {",
    ]
    for name in _STANDARD_NAMES:
        if name not in positions:
            continue
        vec = np.asarray(positions[name], dtype=float)
        x, y, z = vec / np.linalg.norm(vec)
        lines.append(f'    "{name}": ({x:.4f}, {y:.4f}, {z:.4f}),')
    lines += ["}", ""]
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
