"""Generate the CAP-1 baseline experiment configs (WP-4.1/4.2).

Writes one explicit, reviewable YAML per (pool × baseline × regime) into
``configs/experiments/baselines/``. Re-run after changing the grid below; commit the
output. Pools:

* ``devpool``: PhysioNet MI + Cho2017 + Lee2019 (real data; blocked by the license gate
  until WP-1.1 verifies licenses). PhysioNet has ~22 imagery trials per class per
  subject, fewer than the CAP-1 grid needs, so its subjects are skipped **as targets**
  (with recorded reasons) and it contributes as a source dataset.
* ``synthetic``: two synthetic "labs", runnable anywhere (pipeline demonstration only).
* ``physionet``: PhysioNet MI alone (license verified 2026-09-28; the only real dataset
  reachable from cloud sessions). About 22 trials per class allow budgets up to k = 8.
  With a single dataset, regimes are R1 (new people, 64 channels) and R1-Crown (new
  people, Neurosity Crown's 8 sites).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

OUT = Path(__file__).resolve().parents[1] / "configs" / "experiments" / "baselines"

BASELINES: dict[str, tuple[str, dict[str, Any]]] = {
    "b0": ("chance", {}),
    "b1": ("csp_lda_subject", {}),
    "b2": ("ts_lr_subject", {}),
    "b3": ("ts_lr_pooled", {}),
    "b4": ("braindecode", {"architecture": "EEGNet"}),
}

POOLS: dict[str, dict[str, Any]] = {
    "devpool": {
        "datasets": ["cho2017", "lee2019_mi", "physionet_mi"],
        "purpose": "benchmark",
        "ks": [0, 5, 10, 20, 40],
        "n_unlabeled": 20,
        "trial_seconds": 2.0,
    },
    "physionet": {
        "datasets": ["physionet_mi"],
        "purpose": "benchmark",
        "ks": [0, 5, 8],
        "n_unlabeled": 10,
        "trial_seconds": 2.0,
    },
    "synthetic": {
        "datasets": ["synthetic_mi", "synthetic_mi_shifted"],
        "purpose": "benchmark",
        "ks": [0, 5, 10, 20, 40],
        "n_unlabeled": 20,
        "trial_seconds": 2.0,
        "synthetic": {
            "n_subjects": 8,
            "n_trials_per_class": 70,
            "signal_to_noise": 0.5,
            "subject_variability": 1.0,
            "seed": 3,
        },
    },
}

REGIMES: dict[str, dict[str, Any]] = {
    "r1": {"regime": "within_dataset", "n_folds": 5},
    "r2": {"regime": "leave_dataset_out"},
    "r3": {"regime": "leave_dataset_out", "target_montage": "neurosity_crown"},
}

SYNTHETIC_R3_MONTAGE = "bci_iv_2b"  # synthetic channels do not cover the Crown layout

# Pools with their own regime grid (a single dataset has no leave-dataset-out regime).
POOL_REGIMES: dict[str, dict[str, dict[str, Any]]] = {
    "physionet": {
        "r1": {"regime": "within_dataset", "n_folds": 5},
        "r1crown": {
            "regime": "within_dataset",
            "n_folds": 5,
            "target_montage": "neurosity_crown",
        },
    },
}


def regimes_for(pool: str) -> dict[str, dict[str, Any]]:
    """The regime grid of ``pool``."""
    return POOL_REGIMES.get(pool, REGIMES)


def config_for(pool: str, baseline: str, regime: str) -> dict[str, Any]:
    """Build one experiment config as a plain dict."""
    spec = POOLS[pool]
    decoder, params = BASELINES[baseline]
    protocol: dict[str, Any] = {
        **regimes_for(pool)[regime],
        "ks": spec["ks"],
        "n_unlabeled": spec["n_unlabeled"],
        "trial_seconds": spec["trial_seconds"],
        "min_test_per_class": 10,
        "seed": 0,
    }
    if regime == "r3" and pool == "synthetic":
        protocol["target_montage"] = SYNTHETIC_R3_MONTAGE
    if "target_montage" in protocol and decoder == "braindecode":
        protocol["source_montage"] = protocol["target_montage"]  # fixed-montage network
    config: dict[str, Any] = {
        "name": f"{pool}-{baseline}-{regime}",
        "description": (
            f"CAP-1 baseline {baseline.upper()} ({decoder}) on {pool}, regime {regime.upper()}."
        ),
        "purpose": spec["purpose"],
        "datasets": spec["datasets"],
        "decoder": {"name": decoder, "params": params},
        "protocol": protocol,
    }
    if "synthetic" in spec:
        config["synthetic"] = spec["synthetic"]
    return config


def main() -> int:
    """Write every config; print how many were written."""
    OUT.mkdir(parents=True, exist_ok=True)
    count = 0
    for pool in POOLS:
        for baseline in BASELINES:
            for regime in regimes_for(pool):
                path = OUT / f"{pool}_{baseline}_{regime}.yaml"
                header = (
                    "# Generated by scripts/make_baseline_configs.py; edit the script instead.\n"
                )
                body = yaml.safe_dump(config_for(pool, baseline, regime), sort_keys=False)
                path.write_text(header + body, encoding="utf-8")
                count += 1
    print(f"wrote {count} configs to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
